do not reload
domino14/liwords pull request #166
Opened 2020-10-17 21:58 UTC by andy-k

make this a single page application instead of reloading.
this way we can make more sounds because it'll be on a page user has interacted in.

added a way to replace the whole store and (indirectly) reconnect the socket.

most page transitions need it. applied it on all for simplicity. (profile page, about page may not actually need it)

2020-10-18 00:14 UTC, atomiccupcake commented
Seeing quite a few issues.

Presences not loading in lobby most of the time (the players drop down at top of chat)
Active games list (watch tab) isn’t showing games at all unless they started while the user had the lobby open when they started
Return to game button mode not happening at bottom of games list
Match requests aren’t visible to receiver if they have a second tab or didn't have the lobby tab open when the match was sent (like a rematch comes in and they go to the lobby to see - it's not there)

2020-10-18 00:15 UTC, atomiccupcake requested changes
Seeing quite a few issues.

Presences not loading in lobby most of the time (the players drop down at top of chat)
Active games list (watch tab) isn’t showing games at all unless they started while the user had the lobby open when they started
Return to game button mode not happening at bottom of games list
Match requests aren’t visible to receiver if they have a second tab or didn't have the lobby tab open when the match was sent (like a rematch comes in and they go to the lobby to see - it's not there)

2020-10-18 19:15 UTC, domino14 commented
- I could not reproduce `Active games list (watch tab) isn’t showing games at all...` (started a game against the bot, and other user was in the lobby and it shows up in Watch. When I refresh other user, game still shows up)
   
   I also tried never being present in the lobby until the other user starts the game and it's still ok.

- The presences seem ok from what I can tell. Are you sure you don't have some users blocked locally @atomiccupcake ? I had that issue actually and then once I unblocked a local player it was fine.

- Return to Game at the bottom showed up ok when I go back to the lobby

- I saw the "Return to game with MacondoBot" in the lobby, the big blue button at the bottom, after I had resigned my game against the bot, and gone back to the lobby. However, I can't reproduce it. Maybe I'm wrong, but this might also maybe trigger some thought?

- I also did not see any issues with match requests, and I tried your reproduction steps @atomiccupcake 

The only issue I noticed was that one that I can't reproduce, and I'm not 100% sure that it's there. 

Is it possible your local branch was somehow corrupted?

2020-10-18 19:47 UTC, atomiccupcake approved these changes

2020-10-18 19:47 UTC, atomiccupcake commented
Yeah, the database had some bad data. I cleared it out and everything seems okay now.

2020-10-19 00:25 UTC, domino14 commented on liwords-ui/src/gameroom/pool.tsx
> +      </Link>
hmmm.. will this do the right thing? I wonder if this is the right way to have a link there...

2020-10-19 00:39 UTC, domino14 commented on liwords-ui/src/store/store.tsx
> +      <RealStore key={storeId} children={children} />
i really didn't know this could be done -- it essentially just creates an entire new store?

2020-10-19 00:47 UTC, domino14 commented
awesome

2020-10-19 00:47 UTC, merged